=== serezha21/exam_xml/validation.dtd
<!ELEMENT CATALOG (property*)>
<!ELEMENT TITLE ANY>
<!ELEMENT ADDRESS ANY>
<!ELEMENT DATE ANY>
<!ELEMENT PRICE ANY>
<!ELEMENT property ( TITLE | ADDRESS | DATE | PRICE )*>
<!ATTLIST property 
     type (Дом|Квартира|Участок) #REQUIRED>
<!ATTLIST property count CDATA #IMPLIED>

=== serezha21/exam_xml/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="transform.xsl"?>
<!--<!DOCTYPE CATALOG SYSTEM "validation.dtd">-->
<CATALOG xmlns="x-schema:schema.xml">
  <property type="Дом" count="5">
    <TITLE>Дом пятивышка</TITLE>
    <ADDRESS>Ул. нанотехников 816З</ADDRESS>
    <DATE>2017-12-31</DATE>
    <PRICE>3000000</PRICE>
  </property>
  <property type="Квартира" count="3">
    <TITLE>Квартира №777</TITLE>
    <ADDRESS>Ул. нанотехников 816З</ADDRESS>
    <DATE>2017-12-31</DATE>
    <PRICE>3000</PRICE>
  </property>
  <property type="Участок">
    <TITLE>Участок где паслись каровы</TITLE>
    <ADDRESS>Ул. нанотехников 1000-З</ADDRESS>
    <DATE>2017-12-31</DATE>
    <PRICE>1000000</PRICE>
  </property>
</CATALOG>
